### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Chameleon-Coder** [cumsoft/cumsoft#1]
Your username is silly, that's why I like it.

**Comment by baudneo** [comment]
WITAF

**Comment by Chameleon-Coder** [comment]
What on Earthbread did you say @baudneo

**Comment by baudneo** [comment]
Just curious is all, I commented with what I said when I read some google results for 'CumSoft'. Lol.

**Comment by Chameleon-Coder** [comment]
oh.

**Comment by G9-dev-real** [comment]
> Just curious is all, I commented with what I said when I read some google results for 'CumSoft'. Lol.

Follow me back

**Comment by baudneo** [comment]
> > Just curious is all, I commented with what I said when I read some google results for 'CumSoft'. Lol.
> 
> Follow me back

@G9-dev-real 
?

**Comment by G9-dev-real** [comment]
> > > Just curious is all, I commented with what I said when I read some google results for 'CumSoft'. Lol.
> > 
> > 
> > Follow me back
> 
> @G9-dev-real ?

I've said that I need him to follow me back

**Comment by Darik2121** [comment]
Cumsoft follow @G9-dev-real back

**Comment by baudneo** [comment]
@G9-dev-real 
Ok, but why quote my comment? That's what was confusing.

**Comment by Darik2121** [comment]
> @G9-dev-real Ok, but why quote my comment? That's what was confusing.

uhh idk
